# ╭─────────────────────────────────────╮
# │    Arch_user_202 Starship Theme     │
# ╰─────────────────────────────────────╯

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$c_drive_indicator\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

# ╭──────────────────────╮
# │     DIRECTORY        │
# ╰──────────────────────╯
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Manimationss" = " Manimationss"
"Desktop" = ""
"C:\\" = "󰋊 C"
"C:/"  = "󰋊 C"
"WINDOWS" = ""  # Replace with your actual username

# ╭──────────────────────╮
# │     C DRIVE ICON     │
# ╰──────────────────────╯
[env_var.c_drive_indicator]
variable = "ON_C_DRIVE"
format = "[󰋊 C](fg:#e3e5e5 bg:#769ff0) "
disabled = false

# ╭──────────────────────╮
# │    GIT MODULES       │
# ╰──────────────────────╯
[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

# ╭──────────────────────╮
# │     LANGUAGES        │
# ╰──────────────────────╯
[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# ╭──────────────────────╮
# │      TIME            │
# ╰──────────────────────╯
[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = '[[ ⌚ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

# ╭──────────────────────╮
# │   CHARACTER          │
# ╰──────────────────────╯
[character]
success_symbol = "[](bold blue)" #here
error_symbol = "[☠](bold red)"

vicmd_symbol = "[](bold yellow)"
